site_name: schulplots
site_url: https://schulplots.ch23.de
nav:
  - Home: index.md
  - Abbildung: figure.md
  - Achensystem: axes.md
  - Graphen: graph.md
  - Fl√§chen: area.md
  - Geraden: lines.md
  - Beschreibungsdatei: description_file.md
exclude_docs: |
  input/graph*.yaml
use_directory_urls: false
theme:
  name: mkdocs
  locale: de
  nav_style: dark
markdown_extensions:
    - markdown_include.include:
        base_path: docs
