figure:
  height: 10cm
  width: 12cm
  #output_file: plot.pdf
axes_descriptors: 
- axes:
    height: 8cm
    width: 8cm
    x_min: -3
    y_min: -2      
  bottom: 1cm
  left: 1cm
  graphs:
  - function: sin(x)
    label: $\sin(x)$
  - function: x**2
    label: $x^2$
  areas:
  - function:
    - sin(x)
    - x**2
    label: A
    condition: y1 >= y2
    plot_args:
      alpha: 0.3
      color: red
  vlines:
  - x_var: sect_x_1
  
